-- 코드를 입력하세요
SELECT HALF.FLAVOR
FROM FIRST_HALF HALF
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR) JULY
ON HALF.FLAVOR = JULY.FLAVOR
ORDER BY (HALF.TOTAL_ORDER + JULY.TOTAL_ORDER) DESC
LIMIT 3